### ISSUE TITLE
Error: Cannot find module '@wordpress/scripts/config/webpack.config'

### ISSUE THREAD

**Issue by zkmark** [them-es/starter-fse#6]
I try to run 'npm run watch' but it doesn't work I got the following errors

`Error: Cannot find module 'webpack-remove-empty-scripts'
`
I solved it with
`npm install webpack-remove-empty-scripts --save-dev
`

Then I get the following error

`Error: Cannot find module '@wordpress/scripts/config/webpack.config'
`
And try to solve with the following command but it doesn't work

`npm i webpack-dev-server
`

I also saw many outdated packages when installing it

```
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated    
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, 
upgrade your dependencies to the actual version of core-js.

added 657 packages, and audited 658 packages in 27s

57 packages are looking for funding
  run `npm fund` for details

33 vulnerabilities (1 low, 6 high, 26 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by them-es** [comment]
Hi @zkmark,

thanks for reporting this issue. There was an outdated version of `package.json` in the repo and it [has been updated now](https://github.com/them-es/starter-fse/commit/468c66a7c5b468df470b8417d3f5e37cfe3c3d1d).

Please 1. delete `node_modules` from your local theme, 2. replace your `package.json` with the [latest version](https://github.com/them-es/starter-fse/blob/main/package.json) and 3. again execute `npm run watch` to update all dependencies accordingly.

This should also fix the outdated packages warning.
